Added clonality, percent on target and percent duplicates
aidaanva/endorS.py pull request #10
Opened 2022-11-02 14:40 UTC by aidaanva

Add all the functionality discussed in #6

2022-11-02 14:57 UTC, aidaanva commented
@jfy133 you will need to show me how to set up the git actions for the testing

2022-11-11 08:05 UTC, jfy133 requested changes
Mostly formatting!

2022-11-11 08:05 UTC, jfy133 commented on endorS.py
> +        print("WARNING: no reads in the fastq input, Percent on target raw (%) set to 0.000000")
```suggestion
        print("WARNING: no reads in the fastq input, percent on target raw (%) set to 0.000000")
```

2022-11-11 08:05 UTC, jfy133 commented on endorS.py
> +        print("No samtools flagstat --raw provided. \nWARNING: none of the Percent on target stats will be calculated")
```suggestion
        print("No samtools flagstat --raw provided. \nWARNING: none of the percent on target stats will be calculated")
```

2022-11-11 08:05 UTC, jfy133 commented on endorS.py
> +            print("WARNING: no reads in the fastq input, Percent on target raw (%) set to 0.000000")
```suggestion
            print("WARNING: no reads in the fastq input, percent on target raw (%) set to 0.000000")
```

2022-11-11 08:05 UTC, jfy133 commented on endorS.py
> +            print("WARNING: no mapped reads, Percent on target modified (%) set to 0.000000")
shouldn't modified be `quality filtered` here for consistency?

also

```suggestion
            print("WARNING: no mapped reads, percent on target modified (%) set to 0.000000")
```

2022-11-11 08:05 UTC, jfy133 commented on endorS.py
> +        print("No samtools flagstat --qualityfiltered provided. \nWARNING: Percent on target Modified stat will not be calculated")
```suggestion
        print("No samtools flagstat --qualityfiltered provided. \nWARNING: Percent on target modified stat will not be calculated")
```

same here

2022-11-11 08:05 UTC, jfy133 commented on endorS.py
> +            print("WARNING: no reads in the fastq input, Percent on target postDeDup (%) set to 0.000000")
```suggestion
            print("WARNING: no reads in the fastq input, percent on target post-deduplication (%) set to 0.000000")
```

2022-11-11 08:05 UTC, jfy133 commented on endorS.py
> +            print("WARNING: no mapped reads, Percent on target postDeDup (%) set to 0.000000")
```suggestion
            print("WARNING: no mapped reads, Percent on target post-deduplication (%) set to 0.000000")
```

2022-11-11 08:05 UTC, jfy133 commented on endorS.py
> +        print("WARNING: non mapped reads postDeDup and/or preDeDup, check your BAM file. Clonality set to 0.000000")
```suggestion
        print("WARNING: non mapped reads post- and/or pre-deduplication, check your BAM file. Clonality set to 0.000000")
```

2022-11-11 08:05 UTC, jfy133 commented on endorS.py
> +        print("WARNING: non mapped reads postDeDup and/or preDeDup, check your BAM file. Percent Duplicates set to 0.000000")
```suggestion
        print("WARNING: non mapped reads post- and/or pre-deduplication, check your BAM file. Percent duplicates set to 0.000000")
```

2022-11-11 08:05 UTC, jfy133 commented on endorS.py
> +        print("No samtools flagstat --deduplicated provided. \nWARNING: Percent on target postDedup, Clonality and Percent of Duplicates stats will not be calculated!")
```suggestion
        print("No samtools flagstat --deduplicated provided. \nWARNING: Percent on target post-deduplication, clonality and percent of duplicates stats will not be calculated!")
```

2022-11-11 08:05 UTC, jfy133 commented on endorS.py
> +            print("Percent Duplicates (%):", percentDuplicates)
```suggestion
            print("Percent duplicates (%):", percentDuplicates)
```

2022-11-11 08:05 UTC, jfy133 commented on endorS.py
> +            print("Percent on target postDedup (%):", endogenousDeDup)
```suggestion
            print("Percent on target post-deduplication (%):", endogenousDeDup)
```

2022-11-11 08:05 UTC, jfy133 commented on endorS.py
> +        print("Percent on target postDedup (%):", endogenousDeDup)
```suggestion
        print("Percent on target post-deduplication (%):", endogenousDeDup)
```

2022-11-11 08:05 UTC, jfy133 commented on endorS.py
> +                    "percent_duplicates": { "max": 100, "min": 0, "title": "Percent Duplicates (%)", "format": '{:,.2f}'}
```suggestion
                    "percent_duplicates": { "max": 100, "min": 0, "title": "Percent duplicates (%)", "format": '{:,.2f}'}
```

2023-02-03 14:28 UTC, aidaanva commented on endorS.py
> +        %(prog)s calculates Percent on target (aka Endogenous DNA) from samtools flagstat files and print to screen.
it will print the name of the program

2023-02-03 14:40 UTC, aidaanva commented
@jfy133 please recheck the review, I think I did all the requested changes and updated the READ.me properly this time

2023-02-08 08:33 UTC, jfy133 approved these changes
Final tweaks but LGTM otherwise

2023-02-08 08:33 UTC, jfy133 commented on README.md
> +endorS.py calculates Percent on target (aka Endogenous DNA) from samtools flagstat files and print to screen.
```suggestion
endorS.py calculates percent on target (aka Endogenous DNA) from samtools flagstat files and print to screen.
```

2023-02-08 08:33 UTC, jfy133 commented on README.md
> +The Percent on target reported will be different depending on the combination of samtools flagstat provided.
```suggestion
The percent on target reported will be different depending on the combination of samtools flagstat provided.
```

2023-02-08 08:33 UTC, jfy133 commented on README.md
> +This program also calculates clonality (aka Cluster Factor) and percent duplicates when the flagstat file after duplicate removal is provided
```suggestion
This program also calculates clonality (aka 'cluster factor') and percent duplicates when the flagstat file after duplicate removal is provided
```

2023-02-08 08:33 UTC, jfy133 commented on endorS.py
> +"""Script to calculate the Percent on target (aka Endogenous DNA), clonality, and percent of duplicates in a sample from samtools flag stats.
```suggestion
"""Script to calculate the percent on target (aka endogenous DNA), clonality, and percent of duplicates in a sample from samtools flag stats.
```

2023-02-08 08:33 UTC, jfy133 commented on endorS.py
> +        %(prog)s calculates Percent on target (aka Endogenous DNA) from samtools flagstat files and print to screen.
```suggestion
        %(prog)s calculates percent on target (aka Endogenous DNA) from samtools flagstat files and print to screen.
```

2023-02-08 08:33 UTC, jfy133 commented on endorS.py
> +        The Percent on target reported will be different depending on the combination of samtools flagstat provided.
```suggestion
        The percent on target reported will be different depending on the combination of samtools flagstat provided.
```

2023-02-08 08:33 UTC, jfy133 commented on endorS.py
> +        This program also calculates clonality (aka Cluster Factor) and percent duplicates when the flagstat file after duplicate removal is provided
```suggestion
        This program also calculates clonality (aka cluster factor) and percent duplicates when the flagstat file after duplicate removal is provided
```

2023-02-17 09:33 UTC, merged